<?xml version="1.0"?>
<package format="3">
  <name>ds5_ros</name>
  <version>0.1.0</version>
  <description>PS5 DualSense interface node using pydualsense and ROS 2</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>

  <exec_depend>pydualsense</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
